line/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from app.views import *

urlpatterns = [
    url(r'^$', CallbackView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^init$', ContactInit.as_view()),
    url(r'^register$', ContactRegister.as_view()),
    url(r'^register/complete$', ContactRegisterComplete.as_view()),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^favicon.ico$', TemplateView.as_view(template_name='favicon.ico')),
]

handler500 = AppricationError.as_view()

line/forms.py
from django import forms
from django.core.validators import MinLengthValidator

ERROR_MESSAGES = {
    'required': 'required',
    'min_length': 'min_length',
    'max_length': 'max_length',
}


class RegisterForm(forms.Form):
    line_id = forms.CharField(required=True,
                              max_length=255,
                              error_messages=ERROR_MESSAGES)
    email = forms.EmailField(required=True,
                             max_length=255,
                             validators=[MinLengthValidator(3)],
                             error_messages=ERROR_MESSAGES)

templates/faq.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ faq.question }}</title>
    <style>
        body {
            padding: 10px; margin: 0;
            line-height: 1.5;
            font-size: 14px;
        }
        img {
            max-width: 100%; height: auto;
        }
        p {
            margin: 0 0 15px 0;
        }
    </style>
</head>
<body>
{{ faq.answer|safe }}
</body>
</html>

templates/register-complete.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
</head>
<body>
<p>登録ありがとうございます。</p>
</body>
</html>

templates/register.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/style.css">
    <title></title>
</head>
<body>
{% if data.request_data['status'] == 'SF_ERROR' %}
    <p class="alert">エラーです。</p>
{% elif data.request_data['status'] == 'SF_DOES_NOT_DATA' %}
    <p class="alert">存在しません。</p>
{% endif %}
{% if data.registered == True %}
    <p>登録済みです。</p>
{% else %}
    <p>既に登録しているE-Mailアドレスを入力してください。</p>
    <form method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <input type="hidden" name="line_id" value="{{ data.line_id }}">
        <div class="form-row">
            <label class="required" for="id_email">E-Mail:</label>
            <input id="id_email" maxlength="254" name="email" type="email" required value="{% if data.form_data['email'] %}{{ data.form_data['email'] }}{% endif %}">
        </div>
        <div class="submit-row">
            <input type="submit" value="登録">
        </div>
    </form>
{% endif %}
</body>
</html>